### PR TITLE
added uk_UA locale

### PR DESCRIPTION
**Pull request by ieaglle**
added uk_Ua locale as well as some tests

### CODE REVIEW

**Comment by drimacus182** [comment]
@ieaglle Why isn't it merged into mbostock:master?

**Comment by ieaglle** [comment]
@drimacus182 I've found a spelling error, canceled, and forgot about that. I probably should proceed with this.

**Comment by drimacus182** [comment]
@ieaglle It would be nice)

**Comment by mbostock** [comment]
I have added these to d3-format and d3-time-format and they will be published to npmcdn.com on the next patch releases.

**Pull request closed without merging**
