### PR TITLE
Flextree

### LINKED ISSUE #1992: Allow nodeSize for trees to be dynamic [request]
In ticket #317 nodeSize for hierarchical layouts was introduced. 
I love this feature.

I was wondering could this be made dynamic, different sizes for different nodes?

I'm not to good with the entire layout engine, but I'd be happy to be useful where I can.

### PR DESCRIPTION
**Pull request by Klortho**
Fixes #1992.  See the [demo](http://klortho.github.io/d3-flextree/).

See [klortho/d3-flextree](https://github.com/klortho/d3-flextree) for more info.  This is a rewrite of layout/tree.js, based on [this code](https://github.com/cwi-swat/non-layered-tidy-trees) from a 2013 paper, [Drawing Non-layered Tidy Trees in Linear Time](http://oai.cwi.nl/oai/asset/21856/21856B.pdf). A.J. van der Ploeg, 2013.

I also wrote a script to turn it into a plugin, which I listed on your plugin wiki page.

I added a bunch of tests to test/layout/tree-test.js, and there are a lot more tests, include regression tests, [here](http://klortho.github.io/d3-flextree/test/).

### CODE REVIEW

**Comment by Klortho** [comment]
Any chance of this getting out of the icebox? I spent a lot of time trying to make sure it's backwards-compatible. One thing I didn't do was performance testing on it, for comparison with the existing. But I could do that if you want.

**Comment by mbostock** [comment]
Why not release this as a [D3 plugin](http://bost.ocks.org/mike/d3-plugin/) for 4.0?

**Comment by chrisvfritz** [comment]
@mbostock Isn't this a superset of (i.e. improvement over) the existing tree layout?

**Comment by jakefoster** [comment]
Agree with @chrisvfritz completely.  This feels like an enhancement to core, not a plugin.

**Comment by Klortho** [comment]
Now that the new version is out, I'll try to find time to turn this into a plugin this week.

**Comment by mbostock** [comment]
Thanks, @Klortho. Let me know if I can answer any questions related to creating a new D3 plugin / module. My [Let’s Make a (D3) Plugin](https://bost.ocks.org/mike/d3-plugin/) guide should still be up-to-date, if it helps.

**Comment by Klortho** [comment]
@mbostock , since this isn't going into "the trunk" (if that even exists anymore) I am planning on severing backwards-compatibility with the tree layout. The API is not a good fit. Holler if there's any reason not to do that.

**Comment by mbostock** [comment]
Sounds reasonable, though I expect you should still be able to design an API that is compatible with the hierarchy nodes returned by d3.hierarchy and d3.stratify, and otherwise reuse the relevant parts of d3-hierarchy while suiting it to your needs.

**Pull request closed without merging**
