### PR TITLE
docs: warn about impure `force` functions

### LINKED ISSUE #3744: warn about impure `forceSimulation(nodes)` function that can modify its input

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #3744.

### CODE REVIEW

**Comment by mbostock** [comment]
Good idea. I think we should use a warning block, like this:

Screenshot 2023-08-21 at 11 10 17 AM

And we should add a similar warning for d3.forceLink, since that likewise can mutate links.

**Comment by hamirmahal** [comment]
Okay, let me know if there are other changes you'd like to see before merging this.

**Comment by mbostock** [comment]
Sorry, I should have mentioned I started a branch with some wording changes too. I’ll get this merged. Thank you. 👍

**Comment by mbostock** [comment]
Folded into #3755.

**Comment by hamirmahal** [comment]
You're welcome! Thanks for merging this into your branch.

**Pull request closed without merging**
