### PR TITLE
octree and 3d force-directed graph layout

### PR DESCRIPTION
**Pull request by kalenedrael**
An octree and 3d force layout, almost entirely copied off of the existing quadtree and 2d force layout implementations with an extra dimension added. Appropriate tests have been added for the quadtree, but not the force layout.

If it's not appropriate for the base library, perhaps it could be a plugin?

### CODE REVIEW

**Comment by mbostock** [comment]
Thanks for the pull request. I think a plugin does sound more appropriate given than D3 is primarily focused on 2D visualization.

**Comment by amcdnl** [comment]
@kalenedrael did you break this out into its own plugin anywhere?

**Comment by trusktr** [comment]
Live demo?

**Comment by trusktr** [comment]
@kalenedrael Can you please share a link to a plugin version of this? Would be so awesome! :D

**Pull request closed without merging**
