### PR TITLE
D3 slider

### PR DESCRIPTION
**Pull request by caravinden**
D3 min max slider is a d3 experiment for slider

### CODE REVIEW

**Comment by curran** [comment]
Perhaps this is better suited to post as an example on bl.ocks.org?

**Comment by caravinden** [comment]
May I know how can I push my code to examples

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Jun 27, 2016 at 9:08 PM +0530, "Curran Kelleher" <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps this is better suited to post as an example on bl.ocks.org?

-

**Comment by mbostock** [comment]
Go to <https://gist.github.com> and create a Gist with an index.html file, and then it will show up on <https://bl.ocks.org/caravinden>.

**Comment by caravinden** [comment]
Thanks a lot Bostock

Get Outlook for Android<https://aka.ms/ghei36>

**Pull request closed without merging**
