### PR TITLE
Add xExtent and yExtent to d3.behavior.zoom (fixes #1084)

### LINKED ISSUE #1084: Allow to restrict pan when zooming
There is a zoom.scaleExtent() to only allow sensible values, but there is no panExtent() that allows me to preven the graph from scrolling out of the visible area.

That seems to be an oversight?

### PR DESCRIPTION
**Pull request by lebolo**
All of this code was contributed by @mhsmith (https://github.com/mbostock/d3/pull/1299) and reimplemented for the latest d3 version by @lebolo.

These limit all actions to ensure the domain of the corresponding scale always stays within the given extent. As well as panning, zooming actions may also be limited in the zoom-out direction. If more than one of `scaleExtent`, `xExtent` and `yExtent` are provided, the effective bottom end of the scale extent will be the most restrictive of the three.

If `scaleExtent` and `x/yExtent` cannot be satisfied simultaneously (i.e. the lower scale limit implied by `x/yExtent` is above the `scaleExtent`), then `x/yExtent` will take priority.

Simple example: http://bl.ocks.org/mhsmith/5732011
Example with discontinuous and log scales: http://bl.ocks.org/mhsmith/5734904

### CODE REVIEW

**Comment by tgunnoe** [comment]
+1, being used in NASA Worldview

**Comment by c0by** [comment]
+1 this would be very cool

**Comment by lebolo** [comment]
If there's still interest in this, I can take a look at the current merge conflicts.

**Comment by langdonx** [comment]
I am certainly still interested.  I've been using a patched version of d3 that includes this.

**Comment by ocombe** [comment]
This functionality is a must have, any chance to get it merged ?

**Comment by lebolo** [comment]
I deleted the fork this Pull Request was based on some time ago =( I'd be happy to re-fork and update the patch to resolve merge conflicts, but that would mean I submit a new PR. And I'm still not sure if this feature will actually be merged - it's been 8 months now.

@mbostock, @jasondavies, is there any interest in merging this feature in? Any reason why it hasn't yet?

**Comment by 256dpi** [comment]
+1 I would love to have that!

**Comment by satishwaghela** [comment]
+1

**Comment by kasiarachwal** [comment]
+1

**Comment by reppners** [comment]
+1

**Comment by masedesign** [comment]
+1

**Comment by Lbousa38** [comment]
Reply

**Comment by xshaka** [comment]
Will be this feature in some final release?

**Comment by mariusandra** [comment]
+1

**Comment by lebolo** [comment]
This feature has been merged (see #1084)

**Pull request closed without merging**
