### PR TITLE
fixed wye decription

### PR DESCRIPTION
**Pull request by askmike**

### CODE REVIEW

**Comment by mbostock** [comment]
Do you mind changing it to “a Y shape” instead of “an Y-shape symbol”? I would, but I am on mobile.

**Comment by askmike** [comment]
done. I got the text from the [d3-shape README](https://github.com/d3/d3-shape/blob/master/README.md#symbolWye). Want me to change that as well?

**Comment by mbostock** [comment]
My thanks!

**Comment by mbostock** [comment]
Nah, that README looks fine. The text here is abbreviated.

**Pull request merged**
