### PR TITLE
Pointer (and MSPointer) events for the zoom behavior.

### PR DESCRIPTION
**Pull request by lubomirov**
Added support of Pointer events in addition to Touch events

### CODE REVIEW

**Comment by mbostock** [comment]
Fixes #1439. Related #2403.

**Comment by nikoloas** [comment]
Hi, I have just downloaded this version and the pinch zoom/panning is not working for my d3 SVG. Do I need to implement something different to add support for IE11?

**Comment by lubomirov** [comment]
Hi, nikolas, I've made rebase and double-checked my patch suggested here. It works in IE11 (particularly in 11.0.25). With this version you can do zoom with two/three/more fingers (there is an algorithm that considers third finger if second one goes out of zoom area). Thank you for downloading and reminding me about this pull request.

**Comment by nikoloas** [comment]
Many thanks for the heads up, I will download this version and test it tomorrow.

**Comment by Greyjoy** [comment]
Hi, I'm using d3 to draw and manipulate a map and it works fine, excepted on windows mobile devices (pinch zoom and translations by touch are disabled). Maybe those changes could fix it ? Can it be merged with main project ? 
Many thanks for your work.

Leo.

**Pull request closed without merging**
