### PR TITLE
Pointer events for the drag behavior.

### PR DESCRIPTION
**Pull request by natevw**
This makes e.g. [the bubble demo](http://bl.ocks.org/mbostock/9631744) usable via touchscreen on Windows machines, and should remain future proof as other major browsers adopt Pointer Events (and as MS [adds Touch Events](http://blogs.msdn.com/b/ie/archive/2014/07/31/the-mobile-web-should-just-work-for-everyone.aspx) for backwards compatibility on some of their platforms).

## Miscellaneous notes

- Unfortunately, this required an (albeit minor and backwards compatible) addition to d3.mouse. My [original go at this](https://github.com/mbostock/d3/commit/736cc499739373d861d625affbf87991a36736f5) compared the ids itself, which seemed a better encapsulation, but the current drag code now already expects a missing (i.e. falsy) position return value as d3.touch gives so I've followed suit here. May actually be useful to other PE-aware users of d3.mouse I suppose.

- I've made the touch-action setting a bit more careful in this go-'round. I again debated whether or not d3 should be setting a style property like this, but a) it's already doing much crazier DOM hacks when needed for other event handling, b) better to have it work by default for the 99% of cases and have anyone who really has some way for touch-action to remain 'auto' and still get useful work out of d3.drag (they can set back themselves).

- Finally, as a more general comment, I haven't updated d3.zoom to work with PE. In my opinion, that behavior should be leveraging the work in d3.drag (+ one further trivial modification to also pass along the dragId with its events) to track touches in a cross-platform way but that needs a bit further discussion beyond https://github.com/mbostock/d3/issues/1793#issuecomment-38082270 — I have long been using `d3.drag` to track touches on a *parent* element (rather than an actually dragged element) and it works fine by simply adjusting via `.origin()`.

### CODE REVIEW

**Comment by lubomirov** [comment]
Hi, I have a working version of d3.behavior.zoom that fully support MS pointer events. The patch is local to zoom.js file. It's about +100 source lines. It can be compact, I didn't an optimization so far. The minimized js size is about +2Kb to d3.js. Could we join our efforts in the area of support pointer events in D3?

**Comment by mbostock** [comment]
Fixes #2556.

**Comment by nikoloas** [comment]
Hi I have just gone through the truck load of updates to support touch on win8+IE11 and none of these fixes actually work for me.  All I'd like to have is the pinch zoom and panning that is supported by default on a SVG element and when a zoom behavior is implemented.  I have found that adding CSS touch-event:none on the SVG element I am able to pan, however the pinch zoom does not work.  I am guessing this isn't related to your solution, how would this update affect my existing d3 drawing?  
Many thanks!

**Comment by natevw** [comment]
@nikoloas Sorry I missed your questions earlier. Have you found a solution? If not, be warned this patch is probably way out of date.

The new d3-drag is even more like pointer events, although unfortunately pointer events are still not supported: https://github.com/d3/d3-drag/issues/25

Hopefully this work here could be ported over, I haven't taken a look at what that would involve yet.

**Comment by Herst** [comment]
@nikoloas 

Quoting myself from https://github.com/d3/d3/issues/1439#issuecomment-338496133:
> Touch events are in Edge but disabled per default and the setting hidden at about:flags. With this activated zooming in works but zooming out does not. All-in-all the situation is inadequate which is why there might still be need for the implementation of at least some pointer event stuff.
> 
> For what it's worth, here is a simple demo of how to support the pinch zooming gesture for triggering a programmatic zoom (not the browser gesture for doing page zooming): https://mdn.github.io/dom-examples/pointerevents/Pinch_zoom_gestures.html
Maybe I find time for hacking support for this into d3 because pinch-zooming is the only thing in my project which does not work on touch-enabled devices with Windows.
>
> Currently, I am not very motivated to do so though because in MS Edge 16 (Fall Creators Update from few days ago) the renderer process stops working when zooming or programmatically panning on my page (page randomly freezes and reloads, after some reloads a "This page is having a problem reloading" message pops up. This happens when doing programmatic resizing as well, if anyone else has the problem with a d3-related page please tell me so we can report it to Microsoft).

**Pull request closed without merging**
